name: Update Scoop Bucket

on:
  workflow_run:
    workflows: ['Build and Release']
    types:
      - completed

jobs:
  update-scoop:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ropean/scoop-ropean/.github/workflows/update-scoop-call.yml@main
    with:
      tag: ${{ github.event.workflow_run.head_branch }}
      app_name: 'myhosts'
      exe_name: 'MyHosts.exe'
      source_repo: ${{ github.repository }}
      description: 'Hosts file editor utility for Windows'
      homepage: 'https://github.com/ropean/MyHosts'
      license_identifier: 'MIT'
      license_url: 'https://github.com/ropean/MyHosts/blob/main/LICENSE'
      shortcut_name: 'MyHosts'
      shortcut_description: 'Hosts file editor'
      notes: 'MyHosts is a utility that helps you edit and manage the Windows hosts file for network configuration and blocking.'
    secrets:
      source_repo_token: ${{ secrets.GITHUB_TOKEN }}
      deploy_key: ${{ secrets.SCOOP_ROPEAN_DEPLOY_KEY }}
